apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: java-rabbitmq-consumer
spec:
  selector:
    matchLabels:
      app: java-rabbitmq-consumer
  template:
    metadata:
      labels:
        app: java-rabbitmq-consumer
    spec:
      containers:
        - name: java-rabbitmq-consumer
          image: docker.io/tinumistry/javarabbitmqconsumer:1.8
          imagePullPolicy: IfNotPresent
