apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service-receiver-deployment
spec:
  selector:
    matchLabels:
      app: keda-service-receiver
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/scrape: "true"
        prometheus.io/port: "9096"
      labels:
        app: keda-service-receiver
    spec:
      containers:
        - name: keda-service-receiver
          image: docker.io/tinumistry/demokedajavaconsumer:keda1
          ports:
            - containerPort: 9096
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-keda-service
spec:
  type: LoadBalancer
  selector:
    app: keda-service-receiver
  ports:
    - port: 8080            
