apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: java-rabbitmq-consumer
  pollingInterval: 5 # Optional. Default: 30 seconds
  cooldownPeriod: 120 # Optional. Default: 300 seconds
  maxReplicaCount: 20 # Optional. Default: 100
  triggers:
    - type: cron
      metadata:
        cronExpression: "30 17 * * *" # schedule to run at 10 PM IST
        scaleDown:0
