apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: java-rabbitmq-consumer
  cooldownPeriod:  60  
  advanced:                            
    restoreToOriginalReplicaCount: true  
  triggers:
  - type: cron
    metadata:
      timezone: Asia/Kolkata
      start: 40 8 * * *
      end: 42 8 * * *
      desiredReplicas: "2"
  - type: cron
    metadata:
      timezone: Asia/Kolkata
      start: 45 8 * * *
      end: 47 6 * * *
      desiredReplicas: "4"      