apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: spring-boot-keda
spec:
  selector:
    matchLabels:
      app: spring-boot-keda
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: spring-boot-keda
    spec:
      containers:
        - name: spring-boot-keda
          image: docker.io/tinumistry/demokedajava 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 
      service:
        type: LoadBalancer
