apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: my-deployment-scaler
  namespace: my-namespace
spec:
  triggers:
  - type: cron
    metadata:
      cronExpression: "30 17 * * *" # schedule to run at 10 PM IST
    scaleTargetRef:
      deploymentName: java-rabbitmq-consumer
    scaleDown:
      value: 0
