apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: spring-boot-keda
spec:
  selector:
    matchLabels:
      app: spring-boot-keda
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: spring-boot-keda
    spec:
      containers:
        - name: spring-boot-keda
          image: docker.io/tinumistry/demokedajava:keda1 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-keda-service
spec:
  type: LoadBalancer
  selector:
    app: spring-boot-keda
  ports:
    - port: 8080
